---
version: "~> 1.0"

os: linux

language: shell

services:
  - docker

# branches:
#   only:
#   - master

env:
  global:
    - CLUSTER_NAME=p
    - CLUSTER_CREATE=true

cache:
  directories:
  - "cache"

before_install:
  - openssl aes-256-cbc -K $encrypted_78399c9ef4b1_key -iv $encrypted_78399c9ef4b1_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xf secrets.tar
  - "sed -i \"s/^  name: replaceme/  name: ${CLUSTER_NAME}/g\" install-config-*/install-config.yaml"

script:
  - |
    source ./bashrc
    ocp-extract
    if [ "$(ls -A cache)" ]; then
      cp -R cache install-config
      ocp-destroy-cluster && rm -rf install-config cache/*
    fi  
    if ${CLUSTER_CREATE}; then
      ocp-create-cluster && \
      ocp-auth-add-google-provider && \
      ocp-auth-add-cluster-admins && \
      ocp-auth-del-kubeadmin
      cp -a install-config/. cache/
    fi